name: Tests

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: app/uv.lock

      - name: Install dependencies
        run: uv sync --dev --frozen

      - name: Run tests
        run: uv run pytest

      - name: Check lint
        run: uv run ruff check .
